# CastleDigital's Docker Configuration for Magento
# (https://github.com/viniciusnw/magento-docker-digitalOcean)
#
# Version 1.0.0

version: "3"

services:
  app:
    volumes: &appvolumes
      - ./src:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"
      
  cron:
    volumes: *appvolumes