# CastleDigital's Docker Configuration for Magento
# (https://github.com/viniciusnw/magento-docker-digitalOcean)
#
# Version 1.0.0

version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
    - ./docker/certbot/www/:/var/www/certbot/
    - ./docker/nginx/conf/certbot.default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/certbot/conf/:/etc/nginx/ssl/

  certbot:
    image: certbot/certbot:latest
    command: certonly -v --webroot --webroot-path /var/www/certbot/ --email vinicius@castledigital.com.br --agree-tos --staple-ocsp -d dev-magento-runningland.castledigital.com.br
    # command: certonly -v --webroot --webroot-path /var/www/certbot/ --email vinicius@castledigital.com.br --agree-tos -d dev-magento-runningland.castledigital.com.br -d www.dev-magento-runningland.castledigital.com.br
    depends_on:
      - nginx
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/
      - ./docker/certbot/conf/:/etc/letsencrypt/
